[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>", "Jonathan Pallant <github@thejpster.org.uk>"]
description = "A heap allocator for Cortex-M processors"
documentation = "https://docs.rs/alloc-cortex-m"
keywords = ["arm", "cortex-m", "allocator"]
license = "MIT OR Apache-2.0"
name = "alloc-cortex-m"
version = "0.1.0"

[dependencies]
cortex-m = "0.1.5"
linked_list_allocator = "0.2.3"
